# \u5E94\u7528\u7AEF\u53E3
server:
  port: 8801
spring:
  application:
    # \u5E94\u7528\u540D\u79F0
    name: provider-user

# eureka \u914D\u7F6E
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: INFO
