server:
  port: 8002
spring:
  application:
    name: cloud-consumer-feign

# eureka \u914D\u7F6E
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: INFO

